[colors.bright]
black = "0x666666"
blue = "0x3b8eea"
cyan = "0x29b8db"
green = "0x23d18b"
magenta = "0xd670d6"
red = "0xf14c4c"
white = "0xe5e5e5"
yellow = "0xf5f543"

[colors.normal]
black = "0x000000"
blue = "0x2472c8"
cyan = "0x11a8cd"
green = "0x0dbc79"
magenta = "0xbc3fbc"
red = "0xcd3131"
white = "0xe5e5e5"
yellow = "0xe5e510"

[colors.primary]
background = "0x000000"
foreground = "0xeaeaea"

[font]
size = 9.0

[window]
opacity = 0.75
